/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Humanloop from "../../../../api/index";
import * as core from "../../../../core";
import { PromptCallResponse } from "../../../types/PromptCallResponse";
import { PromptCallStreamResponse } from "../../../types/PromptCallStreamResponse";

export const CallPromptsCallPostResponse: core.serialization.Schema<
    serializers.CallPromptsCallPostResponse.Raw,
    Humanloop.CallPromptsCallPostResponse
> = core.serialization.undiscriminatedUnion([PromptCallResponse, PromptCallStreamResponse]);

export declare namespace CallPromptsCallPostResponse {
    type Raw = PromptCallResponse.Raw | PromptCallStreamResponse.Raw;
}
