/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Humanloop from "../../../../api/index";
import * as core from "../../../../core";
import { PromptKernelRequest } from "../../../types/PromptKernelRequest";

export const PromptLogRequestPrompt: core.serialization.Schema<
    serializers.PromptLogRequestPrompt.Raw,
    Humanloop.PromptLogRequestPrompt
> = core.serialization.undiscriminatedUnion([PromptKernelRequest, core.serialization.string()]);

export declare namespace PromptLogRequestPrompt {
    export type Raw = PromptKernelRequest.Raw | string;
}
