tabWidth: 4
printWidth: 88
semi: true
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
trailingComma: "all"
# TODO: This fails at release step, figure it out later
# plugins:
    # - "@trivago/prettier-plugin-sort-imports"
