/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         versionId: "version_id"
 *     }
 */
export interface DeployToolsIdEnvironmentsEnvironmentIdPostRequest {
    /**
     * Unique identifier for the specific version of the Tool.
     */
    versionId: string;
}
