/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListVersionsToolsIdVersionsGetRequest {
    /**
     * Whether to include Evaluator aggregate results for the versions in the response
     */
    evaluatorAggregates?: boolean;
}
