/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         path: "new directory/new name"
 *     }
 */
export interface UpdateToolRequest {
    /** Path of the Tool including the Tool name, which is used as a unique identifier. */
    path?: string;
    /** Name of the Tool, which is used as a unique identifier. */
    name?: string;
}
