/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../../index";

/**
 * @example
 *     {
 *         logId: "log_1234567890",
 *         messages: [{
 *                 role: "tool",
 *                 content: "{\"type\": \"checking\", \"balance\": 5200}",
 *                 toolCallId: "tc_1234567890"
 *             }]
 *     }
 */
export interface AgentsContinueCallRequest {
    /** This identifies the Agent Log to continue. */
    logId: string;
    /** The additional messages with which to continue the Agent Log. Often, these should start with the Tool messages with results for the previous Assistant message's tool calls. */
    messages: Humanloop.ChatMessage[];
    /** API keys required by each provider to make API calls. The API keys provided here are not stored by Humanloop. If not specified here, Humanloop will fall back to the key saved to your organization. */
    providerApiKeys?: Humanloop.ProviderApiKeys;
    /** If true, populate `trace_children` for the returned Agent Log. Defaults to false. */
    includeTraceChildren?: boolean;
}
