/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         size: 1,
 *         fileId: "pr_123abc"
 *     }
 */
export interface ListSessionsGetRequest {
    /**
     * Unique identifier for File to return Sessions for. Sessions that contain any Logs associated to this File will be returned.
     */
    fileId?: string;
    /**
     * Unique identifier for Version to return Sessions for. Sessions that contain any Logs associated to this Version will be returned.
     */
    versionId?: string;
    /**
     * Page number for pagination.
     */
    page?: number;
    /**
     * Page size for pagination. Number of Sessions to fetch.
     */
    size?: number;
}
