/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../../index";

/**
 * @example
 *     {
 *         inputs: {
 *             "question": "Patient with a history of diabetes and normal tension presents with chest pain and shortness of breath."
 *         },
 *         output: "The patient is likely experiencing a myocardial infarction. Immediate medical attention is required.",
 *         logStatus: "complete",
 *         error: undefined
 *     }
 */
export interface UpdateTraceRequest {
    /** List of chat messages that were used as an input to the Flow. */
    messages?: Humanloop.ChatMessage[];
    /** The output message returned by this Flow. */
    outputMessage?: Humanloop.ChatMessage;
    /** The inputs passed to the Flow Log. */
    inputs?: Record<string, unknown>;
    /** The output of the Flow Log. Provide None to unset existing `output` value. Provide either this, `output_message` or `error`. */
    output?: string;
    /** The error message of the Flow Log. Provide None to unset existing `error` value. Provide either this, `output_message` or `output`. */
    error?: string;
    /** Status of the Trace. When a Log is updated from `incomplete` to `complete`, it becomes available to Monitoring Evaluators. */
    logStatus?: Humanloop.LogStatus;
}
