/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * Response model for continuing an Agent call in streaming mode.
 */
export interface AgentContinueStreamResponse {
    logId: string;
    message: string;
    payload?: Humanloop.AgentContinueStreamResponsePayload;
    type: Humanloop.EventType;
    createdAt: Date;
}
