/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface AgentInlineTool {
    type: "inline";
    jsonSchema: Humanloop.ToolFunction;
    onAgentCall?: Humanloop.OnAgentCallEnum;
}
