/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type AgentResponseToolsItem = Humanloop.AgentLinkedFileResponse | Humanloop.AgentInlineTool;
