/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface CategoricalFeedbackLabel {
    value: string;
    /** Whether the feedback sentiment is positive or negative. */
    sentiment: Humanloop.LabelSentiment;
    /** Whether the feedback label is active or inactive. */
    status: Humanloop.FeedbackLabelStatus;
}
