/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface ChatMessage {
    /** The content of the message. */
    content?: Humanloop.ChatMessageContent;
    /** Optional name of the message author. */
    name?: string;
    /** Tool call that this message is responding to. */
    toolCallId?: string;
    /** Role of the message author. */
    role: Humanloop.ChatRole;
    /** A list of tool calls requested by the assistant. */
    toolCalls?: Humanloop.ToolCall[];
}
