/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type ChatMessageThinkingItem = Humanloop.AnthropicThinkingContent | Humanloop.AnthropicRedactedThinkingContent;
