/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface ChatMessageWithToolCall {
    /** The content of the message. */
    content?: Humanloop.ChatMessageWithToolCallContent;
    /** Optional name of the message author. */
    name?: string;
    /** Tool call that this message is responding to. */
    toolCallId?: string;
    /** Role of the message author. */
    role: Humanloop.ChatRole;
    /** A list of tool calls requested by the assistant. */
    toolCalls?: Humanloop.ToolCall[];
    /** NB: Deprecated in favour of tool_calls. A tool call requested by the assistant. */
    toolCall?: Humanloop.FunctionTool;
}
