/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type ConfigResponse =
    | Humanloop.ModelConfigResponse
    | Humanloop.ToolConfigResponse
    | Humanloop.EvaluatorConfigResponse
    | Humanloop.AgentConfigResponse
    | Humanloop.GenericConfigResponse;
