/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * Response for an Agent Log.
 */
export interface CreateAgentLogResponse {
    /** Unique identifier for the Log. */
    id: string;
    /** Unique identifier for the Agent. */
    agentId: string;
    /** Unique identifier for the Agent Version. */
    versionId: string;
    /** Status of the Agent Log. When a Agent Log is marked as `complete`, no more Logs can be added to it. Monitoring Evaluators will only run on `complete` Agent Logs. */
    logStatus?: Humanloop.LogStatus;
}
