/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type DirectoryWithParentsAndChildrenResponseFilesItem =
    | Humanloop.PromptResponse
    | Humanloop.ToolResponse
    | Humanloop.EvaluatorResponse
    | Humanloop.DatasetResponse
    | Humanloop.FlowResponse;
