/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DirectoryResponse {
    /** String ID of directory. Starts with `dir_`. */
    id: string;
    /** ID of the parent directory. Will be `None` if the directory is the root directory. Starts with `dir_`. */
    parentId?: string;
    /** Name of the directory. */
    name: string;
    /** Description of the directory. */
    description?: string;
    /** Path to the directory, relative to the root directory. Includes name, e.g. `path/to/directory`. */
    path: string;
    /** Long description of the directory. */
    readme?: string;
    /** List of tags associated with the directory. */
    tags: string[];
    createdAt: Date;
    updatedAt: Date;
}
