/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface EvaluatorActivationDeactivationRequest {
    /** Monitoring Evaluators to activate. These will be automatically run on new Logs. */
    evaluatorsToActivate?: Humanloop.EvaluatorActivationDeactivationRequestEvaluatorsToActivateItem[];
    /** Evaluators to deactivate. These will not be run on new Logs. */
    evaluatorsToDeactivate?: Humanloop.EvaluatorActivationDeactivationRequestEvaluatorsToDeactivateItem[];
}
