/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Base model for specifying an Evaluator for an Evaluation.
 */
export interface EvaluatorVersionId {
    /** Unique identifier for the Version. */
    versionId: string;
    /** Whether the Evaluator is orchestrated by Humanloop. Default is `True`. If `False`, a log for the Evaluator should be submitted by the user via the API. */
    orchestrated?: boolean;
}
