/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enum representing the possible return types of an evaluator.
 */
export type EvaluatorReturnTypeEnum = "boolean" | "number";

export const EvaluatorReturnTypeEnum = {
    Boolean: "boolean",
    Number: "number",
} as const;
