/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EvaluatorJudgmentNumberLimit {
    /** The minimum value that can be selected. */
    min?: number;
    /** The maximum value that can be selected. */
    max?: number;
    /** The step size for the number input. */
    step?: number;
}
