/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type EvaluatedVersionResponse = Humanloop.PromptResponse | Humanloop.ToolResponse;
