/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EvaluationsDatasetRequest {
    /** Unique identifier for the Dataset Version to use in this evaluation. Starts with `dsv_`. */
    versionId: string;
}
