/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type EvaluatorResponseSpec =
    | Humanloop.LlmEvaluatorRequest
    | Humanloop.CodeEvaluatorRequest
    | Humanloop.HumanEvaluatorRequest;
