/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * Version of the Evaluatee being evaluated.
 */
export interface EvaluateeResponse {
    version?: Humanloop.RunVersionResponse;
    /** Unique identifier for the batch of Logs to include in the Evaluation. */
    batchId?: string;
    /** Whether the Prompt/Tool is orchestrated by Humanloop. Default is `True`. If `False`, a log for the Prompt/Tool should be submitted by the user via the API. */
    orchestrated: boolean;
    /** Pinned Evaluatees are shown in Humanloop's Overview, allowing you to use them as baselines for comparison. */
    pinned: boolean;
    /** When the Evaluatee was added to the Evaluation. */
    addedAt?: Date;
}
