/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface EvaluationResponse {
    /** Unique identifier for the Evaluation. Starts with `evr`. */
    id: string;
    /** The total number of Runs in the Evaluation. */
    runsCount: number;
    /** The Evaluator Versions used to evaluate. */
    evaluators: Humanloop.EvaluationEvaluatorResponse[];
    /** Name of the Evaluation to help identify it. Must be unique among Evaluations associated with File. */
    name?: string;
    /** Unique identifier for the File associated with the Evaluation. */
    fileId?: string;
    createdAt: Date;
    createdBy?: Humanloop.UserResponse | undefined;
    updatedAt: Date;
    /** URL to view the Evaluation on the Humanloop. */
    url?: string;
}
