/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExperimentVersionResponse {
    /** The mean performance of the Version. */
    mean?: number;
    /** The spread of performance of the Version. */
    spread?: number;
    /** Number of datapoints with feedback associated to the experiment. */
    trialsCount: number;
    /** Whether the Version is active in the experiment. Only active model configs can be sampled from the experiment. */
    active: boolean;
    /** String ID of Version. */
    id: string;
    /** Commit message of Version. */
    commitMessage?: string;
    /** Version of the Prompt or Tool. */
    versionId: string;
    createdAt: Date;
    updatedAt: Date;
}
