/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * The version of the File that is deployed to the Environment, if one is deployed.
 */
export type FileEnvironmentResponseFile =
    | Humanloop.PromptResponse
    | Humanloop.ToolResponse
    | Humanloop.DatasetResponse
    | Humanloop.EvaluatorResponse
    | Humanloop.FlowResponse;
