/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specification of a File by its path.
 */
export interface FilePath {
    /** If provided, the Version deployed to this Environment is used. If not provided, the Version deployed to the default Environment is used. */
    environment?: string;
    /** Path identifying a File. Provide this to specify a File. */
    path: string;
}
