/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * Response model for a Flow.
 */
export interface FlowResponse {
    /** Path of the Flow, including the name, which is used as a unique identifier. */
    path: string;
    /** Unique identifier for the Flow. Starts with fl\_. */
    id: string;
    /** ID of the directory that the file is in on Humanloop. */
    directoryId?: string;
    /** A key-value object identifying the Flow Version. */
    attributes: Record<string, unknown>;
    /** Message describing the changes made. If provided, a committed version of the Flow is created. Otherwise, an uncommitted version is created. */
    commitMessage?: string;
    /** Name of the Flow. */
    name: string;
    /** Unique identifier for the specific Flow Version. If no query params provided, the default deployed Flow Version is returned. */
    versionId: string;
    type?: "flow";
    /** The list of environments the Flow Version is deployed to. */
    environments?: Humanloop.EnvironmentResponse[];
    createdAt: Date;
    updatedAt: Date;
    /** The user who created the Flow. */
    createdBy?: Humanloop.UserResponse | undefined;
    /** The status of the Flow Version. */
    status: Humanloop.VersionStatus;
    lastUsedAt: Date;
    /** The number of logs that have been generated for this Flow Version */
    versionLogsCount: number;
    /** Aggregation of Evaluator results for the Flow Version. */
    evaluatorAggregates?: Humanloop.EvaluatorAggregate[];
    /** The list of Monitoring Evaluators associated with the Flow Version. */
    evaluators?: Humanloop.MonitoringEvaluatorResponse[];
}
