/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * Definition of tool within a model config.
 *
 * The subset of ToolConfig parameters received by the chat endpoint.
 * Does not have things like the signature or setup schema.
 */
export interface ModelConfigToolRequest {
    /** The name of the tool shown to the model. */
    name: string;
    /** The description of the tool shown to the model. */
    description?: string;
    /** Definition of parameters needed to run the tool. Provided in jsonschema format: https://json-schema.org/ */
    parameters?: Record<string, unknown>;
    /** Source of the tool. If defined at an organization level will be 'organization' else 'inline'. */
    source?: Humanloop.ToolSource;
    /** Code source of the tool. */
    sourceCode?: string;
    /** Other parameters that define the config. */
    other?: Record<string, unknown>;
    /** If is_preset = true, this is the name of the preset tool on Humanloop. This is used as the key to look up the Humanloop runtime of the tool */
    presetName?: string;
}
