/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * State of an evaluator connected to a file
 */
export type MonitoringEvaluatorState = "active" | "inactive";

export const MonitoringEvaluatorState = {
    Active: "active",
    Inactive: "inactive",
} as const;
