/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * What an Agent should do when calling a Tool.
 */
export type OnAgentCallEnum = "stop" | "continue";
export const OnAgentCallEnum = {
    Stop: "stop",
    Continue: "continue",
} as const;
