/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface PaginatedDataEvaluatorResponse {
    records: Humanloop.EvaluatorResponse[];
    page: number;
    size: number;
    total: number;
}
