/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface PaginatedDataUnionPromptResponseToolResponseDatasetResponseEvaluatorResponse {
    records: Humanloop.PaginatedDataUnionPromptResponseToolResponseDatasetResponseEvaluatorResponseRecordsItem[];
    page: number;
    size: number;
    total: number;
}
