/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type PaginatedDataUnionPromptResponseToolResponseDatasetResponseEvaluatorResponseRecordsItem =
    | Humanloop.PromptResponse
    | Humanloop.ToolResponse
    | undefined
    | Humanloop.DatasetResponse
    | Humanloop.EvaluatorResponse;
