/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * The template populated with the input values you provided in the request. Returns None if no template exists.
 */
export type PopulateTemplateResponsePopulatedTemplate = string | Humanloop.ChatMessage[];
