/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * Response format of the model.
 */
export interface ResponseFormat {
    type: Humanloop.ResponseFormatType;
    /** The JSON schema of the response format if type is json_schema. */
    jsonSchema?: Record<string, unknown>;
}
