/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type RunStatsResponseEvaluatorStatsItem =
    | Humanloop.NumericEvaluatorStatsResponse
    | Humanloop.BooleanEvaluatorStatsResponse
    | Humanloop.SelectEvaluatorStatsResponse
    | Humanloop.TextEvaluatorStatsResponse;
