/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type SortOrder = "asc" | "desc";
export const SortOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
