/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export type SrcExternalAppModelsV5LogsLogResponse =
    | Humanloop.PromptLogResponse
    | Humanloop.ToolLogResponse
    | Humanloop.EvaluatorLogResponse;
