/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Template engine to use for rendering templates.
 */
export type TemplateLanguage = "default" | "jinja";
export const TemplateLanguage = {
    Default: "default",
    Jinja: "jinja",
} as const;
