/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type TimeUnit = "day" | "week" | "month";

export const TimeUnit = {
    Day: "day",
    Week: "week",
    Month: "month",
} as const;
