/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

export interface ToolConfigResponse {
    /** String ID of config. Starts with `config_`. */
    id: string;
    /** Other parameters that define the config. */
    other?: Record<string, unknown>;
    type: "tool";
    /** The user who created the config. */
    createdBy?: Humanloop.BaseModelsUserResponse;
    /** Whether the config is committed or not. */
    status: string;
    /** Name for the tool referenced by the model. */
    name: string;
    /** Description of the tool referenced by the model */
    description?: string;
    /** Source of the tool. If defined at an organization level will be 'organization' else 'inline'. */
    source?: Humanloop.ToolSource;
    /** Code source of the tool. */
    sourceCode?: string;
    /** Definition of parameters needed to run the tool. Provided in jsonschema format: https://json-schema.org/ */
    setupSchema?: Record<string, unknown>;
    /** Definition of parameters needed to run the tool. Provided in jsonschema format: https://json-schema.org/ */
    parameters?: Record<string, unknown>;
    /** The function signature of the tool when being called. */
    signature?: string;
    /** Whether the tool is one where Humanloop defines runtime or not. */
    isPreset?: boolean;
    /** If is_preset = true, this is the name of the preset tool on Humanloop. This is used as the key to lookup the Humanloop runtime of the tool */
    presetName?: string;
}
