/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type TraceStatus = "complete" | "incomplete";

export const TraceStatus = {
    Complete: "complete",
    Incomplete: "incomplete",
} as const;
