/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../index";

/**
 * The specific Version being referenced.
 */
export type VersionIdResponseVersion =
    | Humanloop.PromptResponse
    | Humanloop.ToolResponse
    | Humanloop.DatasetResponse
    | Humanloop.EvaluatorResponse
    | Humanloop.FlowResponse
    | Humanloop.AgentResponse;
