/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Humanloop from "../../../../api/index";
import * as core from "../../../../core";
import { DatasetResponse } from "../../../types/DatasetResponse";

export const RetrieveByPathFilesRetrieveByPathPostResponse: core.serialization.Schema<
    serializers.RetrieveByPathFilesRetrieveByPathPostResponse.Raw,
    Humanloop.RetrieveByPathFilesRetrieveByPathPostResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(() => serializers.PromptResponse),
    core.serialization.lazyObject(() => serializers.ToolResponse),
    DatasetResponse,
    core.serialization.lazyObject(() => serializers.EvaluatorResponse),
    core.serialization.lazyObject(() => serializers.FlowResponse),
]);

export declare namespace RetrieveByPathFilesRetrieveByPathPostResponse {
    type Raw =
        | serializers.PromptResponse.Raw
        | serializers.ToolResponse.Raw
        | DatasetResponse.Raw
        | serializers.EvaluatorResponse.Raw
        | serializers.FlowResponse.Raw;
}
