/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../index";

/**
 * The template contains the main structure and instructions for the model, including input variables for dynamic values.
 *
 * For chat models, provide the template as a ChatTemplate (a list of messages), e.g. a system message, followed by a user message with an input variable.
 * For completion models, provide a prompt template as a string.
 *
 * Input variables should be specified with double curly bracket syntax: `{{input_name}}`.
 */
export type PromptRequestTemplate = string | Humanloop.ChatMessage[];
