/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Humanloop from "../../../../api/index";
import * as core from "../../../../core";
import { LlmEvaluatorRequest } from "../../../types/LlmEvaluatorRequest";
import { CodeEvaluatorRequest } from "../../../types/CodeEvaluatorRequest";
import { HumanEvaluatorRequest } from "../../../types/HumanEvaluatorRequest";
import { ExternalEvaluatorRequest } from "../../../types/ExternalEvaluatorRequest";

export const SrcExternalAppModelsV5EvaluatorsEvaluatorRequestSpec: core.serialization.Schema<
    serializers.SrcExternalAppModelsV5EvaluatorsEvaluatorRequestSpec.Raw,
    Humanloop.SrcExternalAppModelsV5EvaluatorsEvaluatorRequestSpec
> = core.serialization.undiscriminatedUnion([
    LlmEvaluatorRequest,
    CodeEvaluatorRequest,
    HumanEvaluatorRequest,
    ExternalEvaluatorRequest,
]);

export declare namespace SrcExternalAppModelsV5EvaluatorsEvaluatorRequestSpec {
    type Raw =
        | LlmEvaluatorRequest.Raw
        | CodeEvaluatorRequest.Raw
        | HumanEvaluatorRequest.Raw
        | ExternalEvaluatorRequest.Raw;
}
