/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Humanloop from "../../../../../api/index";
import * as core from "../../../../../core";
import { ChatMessage } from "../../../../types/ChatMessage";
import { AgentsCallRequestToolChoice } from "../../types/AgentsCallRequestToolChoice";
import { AgentKernelRequest } from "../../../../types/AgentKernelRequest";
import { LogStatus } from "../../../../types/LogStatus";
import { ProviderApiKeys } from "../../../../types/ProviderApiKeys";

export const AgentsCallRequest: core.serialization.Schema<
    serializers.AgentsCallRequest.Raw,
    Omit<Humanloop.AgentsCallRequest, "versionId" | "environment">
> = core.serialization.object({
    path: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    messages: core.serialization.list(ChatMessage).optional(),
    toolChoice: core.serialization.property("tool_choice", AgentsCallRequestToolChoice.optional()),
    agent: AgentKernelRequest.optional(),
    inputs: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    source: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    startTime: core.serialization.property("start_time", core.serialization.date().optional()),
    endTime: core.serialization.property("end_time", core.serialization.date().optional()),
    logStatus: core.serialization.property("log_status", LogStatus.optional()),
    sourceDatapointId: core.serialization.property("source_datapoint_id", core.serialization.string().optional()),
    traceParentId: core.serialization.property("trace_parent_id", core.serialization.string().optional()),
    user: core.serialization.string().optional(),
    agentsCallRequestEnvironment: core.serialization.property("environment", core.serialization.string().optional()),
    save: core.serialization.boolean().optional(),
    logId: core.serialization.property("log_id", core.serialization.string().optional()),
    providerApiKeys: core.serialization.property("provider_api_keys", ProviderApiKeys.optional()),
    returnInputs: core.serialization.property("return_inputs", core.serialization.boolean().optional()),
    includeTraceChildren: core.serialization.property(
        "include_trace_children",
        core.serialization.boolean().optional(),
    ),
});

export declare namespace AgentsCallRequest {
    export interface Raw {
        path?: string | null;
        id?: string | null;
        messages?: ChatMessage.Raw[] | null;
        tool_choice?: AgentsCallRequestToolChoice.Raw | null;
        agent?: AgentKernelRequest.Raw | null;
        inputs?: Record<string, unknown> | null;
        source?: string | null;
        metadata?: Record<string, unknown> | null;
        start_time?: string | null;
        end_time?: string | null;
        log_status?: LogStatus.Raw | null;
        source_datapoint_id?: string | null;
        trace_parent_id?: string | null;
        user?: string | null;
        environment?: string | null;
        save?: boolean | null;
        log_id?: string | null;
        provider_api_keys?: ProviderApiKeys.Raw | null;
        return_inputs?: boolean | null;
        include_trace_children?: boolean | null;
    }
}
