/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Humanloop from "../../../../../api/index";
import * as core from "../../../../../core";
import { ChatMessage } from "../../../../types/ChatMessage";
import { ProviderApiKeys } from "../../../../types/ProviderApiKeys";

export const AgentsContinueCallStreamRequest: core.serialization.Schema<
    serializers.AgentsContinueCallStreamRequest.Raw,
    Humanloop.AgentsContinueCallStreamRequest
> = core.serialization.object({
    logId: core.serialization.property("log_id", core.serialization.string()),
    messages: core.serialization.list(ChatMessage),
    providerApiKeys: core.serialization.property("provider_api_keys", ProviderApiKeys.optional()),
    includeTraceChildren: core.serialization.property(
        "include_trace_children",
        core.serialization.boolean().optional(),
    ),
});

export declare namespace AgentsContinueCallStreamRequest {
    export interface Raw {
        log_id: string;
        messages: ChatMessage.Raw[];
        provider_api_keys?: ProviderApiKeys.Raw | null;
        include_trace_children?: boolean | null;
    }
}
