/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Humanloop from "../../../../../api/index";
import * as core from "../../../../../core";

export const BodyDeserializeAgentsDeserializePost: core.serialization.Schema<
    serializers.BodyDeserializeAgentsDeserializePost.Raw,
    Humanloop.BodyDeserializeAgentsDeserializePost
> = core.serialization.object({
    agent: core.serialization.string(),
});

export declare namespace BodyDeserializeAgentsDeserializePost {
    export interface Raw {
        agent: string;
    }
}
