/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Humanloop from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpdateAgentRequest: core.serialization.Schema<
    serializers.UpdateAgentRequest.Raw,
    Humanloop.UpdateAgentRequest
> = core.serialization.object({
    path: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    directoryId: core.serialization.property("directory_id", core.serialization.string().optional()),
});

export declare namespace UpdateAgentRequest {
    export interface Raw {
        path?: string | null;
        name?: string | null;
        directory_id?: string | null;
    }
}
