/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../index";

/**
 * Version to use in this Run.
 */
export type CreateRunRequestVersion = Humanloop.VersionId | Humanloop.FileId | Humanloop.FilePath;
