/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface PopulatePromptsIdPopulatePostRequest {
    /**
     * A specific Version ID of the Prompt to retrieve to populate the template.
     */
    versionId?: string;
    /**
     * Name of the Environment to retrieve a deployed Version from to populate the template.
     */
    environment?: string;
    body: Record<string, unknown>;
}
