/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdatePromptRequest {
    /** Path of the Prompt including the Prompt name, which is used as a unique identifier. */
    path?: string;
    /** Name of the Prompt. */
    name?: string;
}
