/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { OpenAiReasoningEffort } from "./OpenAiReasoningEffort";

export const AgentKernelRequestReasoningEffort: core.serialization.Schema<
    serializers.AgentKernelRequestReasoningEffort.Raw,
    Humanloop.AgentKernelRequestReasoningEffort
> = core.serialization.undiscriminatedUnion([OpenAiReasoningEffort, core.serialization.number()]);

export declare namespace AgentKernelRequestReasoningEffort {
    export type Raw = OpenAiReasoningEffort.Raw | number;
}
