/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { LinkedFileRequest } from "./LinkedFileRequest";
import { OnAgentCallEnum } from "./OnAgentCallEnum";

export const AgentLinkedFileRequest: core.serialization.ObjectSchema<
    serializers.AgentLinkedFileRequest.Raw,
    Humanloop.AgentLinkedFileRequest
> = core.serialization.object({
    type: core.serialization.stringLiteral("file"),
    link: LinkedFileRequest,
    onAgentCall: core.serialization.property("on_agent_call", OnAgentCallEnum.optional()),
});

export declare namespace AgentLinkedFileRequest {
    export interface Raw {
        type: "file";
        link: LinkedFileRequest.Raw;
        on_agent_call?: OnAgentCallEnum.Raw | null;
    }
}
