/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { AgentContinueStreamResponsePayload } from "./AgentContinueStreamResponsePayload";
import { EventType } from "./EventType";

export const AgentContinueStreamResponse: core.serialization.ObjectSchema<
    serializers.AgentContinueStreamResponse.Raw,
    Humanloop.AgentContinueStreamResponse
> = core.serialization.object({
    logId: core.serialization.property("log_id", core.serialization.string()),
    message: core.serialization.string(),
    payload: AgentContinueStreamResponsePayload.optional(),
    type: EventType,
});

export declare namespace AgentContinueStreamResponse {
    export interface Raw {
        log_id: string;
        message: string;
        payload?: AgentContinueStreamResponsePayload.Raw | null;
        type: EventType.Raw;
    }
}
