/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const BaseModelsUserResponse: core.serialization.Schema<
    serializers.BaseModelsUserResponse.Raw,
    Humanloop.BaseModelsUserResponse
> = core.serialization.unknown();

export declare namespace BaseModelsUserResponse {
    type Raw = unknown;
}
