/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { AnthropicThinkingContent } from "./AnthropicThinkingContent";
import { AnthropicRedactedThinkingContent } from "./AnthropicRedactedThinkingContent";

export const ChatMessageThinkingItem: core.serialization.Schema<
    serializers.ChatMessageThinkingItem.Raw,
    Humanloop.ChatMessageThinkingItem
> = core.serialization.undiscriminatedUnion([AnthropicThinkingContent, AnthropicRedactedThinkingContent]);

export declare namespace ChatMessageThinkingItem {
    export type Raw = AnthropicThinkingContent.Raw | AnthropicRedactedThinkingContent.Raw;
}
