/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { TextChatContent } from "./TextChatContent";
import { ImageChatContent } from "./ImageChatContent";

export const ChatMessageWithToolCallContentItem: core.serialization.Schema<
    serializers.ChatMessageWithToolCallContentItem.Raw,
    Humanloop.ChatMessageWithToolCallContentItem
> = core.serialization.undiscriminatedUnion([TextChatContent, ImageChatContent]);

export declare namespace ChatMessageWithToolCallContentItem {
    type Raw = TextChatContent.Raw | ImageChatContent.Raw;
}
