/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const CreateDatapointRequestTargetValue: core.serialization.Schema<
    serializers.CreateDatapointRequestTargetValue.Raw,
    Humanloop.CreateDatapointRequestTargetValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.boolean(),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    core.serialization.list(core.serialization.unknown()),
]);

export declare namespace CreateDatapointRequestTargetValue {
    type Raw = string | number | number | boolean | Record<string, unknown> | unknown[];
}
