/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const CreatePromptLogResponse: core.serialization.ObjectSchema<
    serializers.CreatePromptLogResponse.Raw,
    Humanloop.CreatePromptLogResponse
> = core.serialization.object({
    id: core.serialization.string(),
    promptId: core.serialization.property("prompt_id", core.serialization.string()),
    versionId: core.serialization.property("version_id", core.serialization.string()),
    sessionId: core.serialization.property("session_id", core.serialization.string().optional()),
});

export declare namespace CreatePromptLogResponse {
    export interface Raw {
        id: string;
        prompt_id: string;
        version_id: string;
        session_id?: string | null;
    }
}
