/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const DatapointResponseTargetValue: core.serialization.Schema<
    serializers.DatapointResponseTargetValue.Raw,
    Humanloop.DatapointResponseTargetValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.boolean(),
    core.serialization.list(core.serialization.unknown()),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
]);

export declare namespace DatapointResponseTargetValue {
    export type Raw = string | number | number | boolean | unknown[] | Record<string, unknown>;
}
