/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const EvaluationsDatasetRequest: core.serialization.ObjectSchema<
    serializers.EvaluationsDatasetRequest.Raw,
    Humanloop.EvaluationsDatasetRequest
> = core.serialization.object({
    versionId: core.serialization.property("version_id", core.serialization.string()),
});

export declare namespace EvaluationsDatasetRequest {
    interface Raw {
        version_id: string;
    }
}
