/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { EvaluatedVersionResponse } from "./EvaluatedVersionResponse";

export const EvaluateeResponse: core.serialization.ObjectSchema<
    serializers.EvaluateeResponse.Raw,
    Humanloop.EvaluateeResponse
> = core.serialization.object({
    version: EvaluatedVersionResponse,
    batchId: core.serialization.property("batch_id", core.serialization.string().optional()),
    orchestrated: core.serialization.boolean(),
});

export declare namespace EvaluateeResponse {
    interface Raw {
        version: EvaluatedVersionResponse.Raw;
        batch_id?: string | null;
        orchestrated: boolean;
    }
}
