/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { OverallStats } from "./OverallStats";
import { VersionStats } from "./VersionStats";

export const EvaluationStats: core.serialization.ObjectSchema<
    serializers.EvaluationStats.Raw,
    Humanloop.EvaluationStats
> = core.serialization.object({
    overallStats: core.serialization.property("overall_stats", OverallStats),
    versionStats: core.serialization.property("version_stats", core.serialization.list(VersionStats)),
});

export declare namespace EvaluationStats {
    interface Raw {
        overall_stats: OverallStats.Raw;
        version_stats: VersionStats.Raw[];
    }
}
