/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const EvaluationsRequest: core.serialization.Schema<
    serializers.EvaluationsRequest.Raw,
    Humanloop.EvaluationsRequest
> = core.serialization.unknown();

export declare namespace EvaluationsRequest {
    export type Raw = unknown;
}
