/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { EvaluatorArgumentsType } from "./EvaluatorArgumentsType";
import { EvaluatorReturnTypeEnum } from "./EvaluatorReturnTypeEnum";

export const ExternalEvaluatorRequest: core.serialization.ObjectSchema<
    serializers.ExternalEvaluatorRequest.Raw,
    Humanloop.ExternalEvaluatorRequest
> = core.serialization.object({
    argumentsType: core.serialization.property("arguments_type", EvaluatorArgumentsType),
    returnType: core.serialization.property("return_type", EvaluatorReturnTypeEnum),
    evaluatorType: core.serialization.property("evaluator_type", core.serialization.stringLiteral("external")),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace ExternalEvaluatorRequest {
    interface Raw {
        arguments_type: EvaluatorArgumentsType.Raw;
        return_type: EvaluatorReturnTypeEnum.Raw;
        evaluator_type: "external";
        metadata?: Record<string, unknown> | null;
    }
}
