/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const FeedbackClass: core.serialization.Schema<serializers.FeedbackClass.Raw, Humanloop.FeedbackClass> =
    core.serialization.enum_(["select", "multi_select", "text", "number"]);

export declare namespace FeedbackClass {
    type Raw = "select" | "multi_select" | "text" | "number";
}
