/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { FeedbackTypeModel } from "./FeedbackTypeModel";

export const FeedbackTypes: core.serialization.Schema<serializers.FeedbackTypes.Raw, Humanloop.FeedbackTypes> =
    core.serialization.list(FeedbackTypeModel);

export declare namespace FeedbackTypes {
    type Raw = FeedbackTypeModel.Raw[];
}
