/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const FileType: core.serialization.Schema<serializers.FileType.Raw, Humanloop.FileType> =
    core.serialization.enum_(["prompt", "tool", "dataset", "evaluator", "flow", "agent"]);

export declare namespace FileType {
    export type Raw = "prompt" | "tool" | "dataset" | "evaluator" | "flow" | "agent";
}
