/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const FileEnvironmentVariableRequest: core.serialization.ObjectSchema<
    serializers.FileEnvironmentVariableRequest.Raw,
    Humanloop.FileEnvironmentVariableRequest
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.string(),
});

export declare namespace FileEnvironmentVariableRequest {
    export interface Raw {
        name: string;
        value: string;
    }
}
