/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { EvaluatorArgumentsType } from "./EvaluatorArgumentsType";
import { EvaluatorReturnTypeEnum } from "./EvaluatorReturnTypeEnum";

export const HumanEvaluatorRequest: core.serialization.ObjectSchema<
    serializers.HumanEvaluatorRequest.Raw,
    Humanloop.HumanEvaluatorRequest
> = core.serialization.object({
    argumentsType: core.serialization.property("arguments_type", EvaluatorArgumentsType),
    returnType: core.serialization.property("return_type", EvaluatorReturnTypeEnum),
    evaluatorType: core.serialization.property("evaluator_type", core.serialization.stringLiteral("human")),
});

export declare namespace HumanEvaluatorRequest {
    interface Raw {
        arguments_type: EvaluatorArgumentsType.Raw;
        return_type: EvaluatorReturnTypeEnum.Raw;
        evaluator_type: "human";
    }
}
