/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const InputResponse: core.serialization.ObjectSchema<serializers.InputResponse.Raw, Humanloop.InputResponse> =
    core.serialization.object({
        name: core.serialization.string(),
    });

export declare namespace InputResponse {
    export interface Raw {
        name: string;
    }
}
