/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const ListEvaluators: core.serialization.ObjectSchema<serializers.ListEvaluators.Raw, Humanloop.ListEvaluators> =
    core.serialization.object({
        records: core.serialization.list(core.serialization.lazyObject(() => serializers.EvaluatorResponse)),
    });

export declare namespace ListEvaluators {
    export interface Raw {
        records: serializers.EvaluatorResponse.Raw[];
    }
}
