/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const ListAgents: core.serialization.ObjectSchema<serializers.ListAgents.Raw, Humanloop.ListAgents> =
    core.serialization.object({
        records: core.serialization.list(core.serialization.lazyObject(() => serializers.AgentResponse)),
    });

export declare namespace ListAgents {
    export interface Raw {
        records: serializers.AgentResponse.Raw[];
    }
}
