/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const MetricValueResponse: core.serialization.ObjectSchema<
    serializers.MetricValueResponse.Raw,
    Humanloop.MetricValueResponse
> = core.serialization.object({
    metricId: core.serialization.property("metric_id", core.serialization.string()),
    metricName: core.serialization.property("metric_name", core.serialization.string()),
    metricValue: core.serialization.property("metric_value", core.serialization.number()),
});

export declare namespace MetricValueResponse {
    interface Raw {
        metric_id: string;
        metric_name: string;
        metric_value: number;
    }
}
