/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const MonitoringEvaluatorState: core.serialization.Schema<
    serializers.MonitoringEvaluatorState.Raw,
    Humanloop.MonitoringEvaluatorState
> = core.serialization.enum_(["active", "inactive"]);

export declare namespace MonitoringEvaluatorState {
    type Raw = "active" | "inactive";
}
