/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const PaginatedDataToolResponse: core.serialization.ObjectSchema<
    serializers.PaginatedDataToolResponse.Raw,
    Humanloop.PaginatedDataToolResponse
> = core.serialization.object({
    records: core.serialization.list(core.serialization.lazyObject(() => serializers.ToolResponse)),
    page: core.serialization.number(),
    size: core.serialization.number(),
    total: core.serialization.number(),
});

export declare namespace PaginatedDataToolResponse {
    interface Raw {
        records: serializers.ToolResponse.Raw[];
        page: number;
        size: number;
        total: number;
    }
}
