/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { DatasetResponse } from "./DatasetResponse";

export const PaginatedDatasetResponse: core.serialization.ObjectSchema<
    serializers.PaginatedDatasetResponse.Raw,
    Humanloop.PaginatedDatasetResponse
> = core.serialization.object({
    records: core.serialization.list(DatasetResponse),
    page: core.serialization.number(),
    size: core.serialization.number(),
    total: core.serialization.number(),
});

export declare namespace PaginatedDatasetResponse {
    export interface Raw {
        records: DatasetResponse.Raw[];
        page: number;
        size: number;
        total: number;
    }
}
