/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const PositiveLabel: core.serialization.ObjectSchema<serializers.PositiveLabel.Raw, Humanloop.PositiveLabel> =
    core.serialization.object({
        type: core.serialization.string(),
        value: core.serialization.string(),
    });

export declare namespace PositiveLabel {
    interface Raw {
        type: string;
        value: string;
    }
}
