/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { ChatMessage } from "./ChatMessage";

export const PromptResponseTemplate: core.serialization.Schema<
    serializers.PromptResponseTemplate.Raw,
    Humanloop.PromptResponseTemplate
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.list(ChatMessage)]);

export declare namespace PromptResponseTemplate {
    export type Raw = string | ChatMessage.Raw[];
}
