/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const ResponseFormat: core.serialization.ObjectSchema<serializers.ResponseFormat.Raw, Humanloop.ResponseFormat> =
    core.serialization.object({
        type: core.serialization.stringLiteral("json_object"),
    });

export declare namespace ResponseFormat {
    interface Raw {
        type: "json_object";
    }
}
