/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { NumericEvaluatorStatsResponse } from "./NumericEvaluatorStatsResponse";
import { BooleanEvaluatorStatsResponse } from "./BooleanEvaluatorStatsResponse";
import { SelectEvaluatorStatsResponse } from "./SelectEvaluatorStatsResponse";
import { TextEvaluatorStatsResponse } from "./TextEvaluatorStatsResponse";

export const RunStatsResponseEvaluatorStatsItem: core.serialization.Schema<
    serializers.RunStatsResponseEvaluatorStatsItem.Raw,
    Humanloop.RunStatsResponseEvaluatorStatsItem
> = core.serialization.undiscriminatedUnion([
    NumericEvaluatorStatsResponse,
    BooleanEvaluatorStatsResponse,
    SelectEvaluatorStatsResponse,
    TextEvaluatorStatsResponse,
]);

export declare namespace RunStatsResponseEvaluatorStatsItem {
    type Raw =
        | NumericEvaluatorStatsResponse.Raw
        | BooleanEvaluatorStatsResponse.Raw
        | SelectEvaluatorStatsResponse.Raw
        | TextEvaluatorStatsResponse.Raw;
}
