/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { SrcExternalAppModelsV5LogsLogResponse } from "./SrcExternalAppModelsV5LogsLogResponse";

export const SessionResponse: core.serialization.ObjectSchema<
    serializers.SessionResponse.Raw,
    Humanloop.SessionResponse
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    logs: core.serialization.list(SrcExternalAppModelsV5LogsLogResponse),
});

export declare namespace SessionResponse {
    interface Raw {
        id: string;
        created_at: string;
        updated_at: string;
        logs: SrcExternalAppModelsV5LogsLogResponse.Raw[];
    }
}
