/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const ToolFunction: core.serialization.ObjectSchema<serializers.ToolFunction.Raw, Humanloop.ToolFunction> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string(),
        strict: core.serialization.boolean().optional(),
        parameters: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace ToolFunction {
    export interface Raw {
        name: string;
        description: string;
        strict?: boolean | null;
        parameters?: Record<string, unknown> | null;
    }
}
