/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const Valence: core.serialization.Schema<serializers.Valence.Raw, Humanloop.Valence> = core.serialization.enum_([
    "positive",
    "negative",
    "neutral",
]);

export declare namespace Valence {
    export type Raw = "positive" | "negative" | "neutral";
}
