/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";

export const VersionReferenceResponse: core.serialization.Schema<
    serializers.VersionReferenceResponse.Raw,
    Humanloop.VersionReferenceResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(() => serializers.VersionDeploymentResponse),
    core.serialization.lazyObject(() => serializers.VersionIdResponse),
]);

export declare namespace VersionReferenceResponse {
    type Raw = serializers.VersionDeploymentResponse.Raw | serializers.VersionIdResponse.Raw;
}
