/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Humanloop from "../../api/index";
import * as core from "../../core";
import { PromptResponse } from "./PromptResponse";
import { ToolResponse } from "./ToolResponse";
import { DatasetResponse } from "./DatasetResponse";
import { EvaluatorResponse } from "./EvaluatorResponse";

export const VersionIdResponseVersion: core.serialization.Schema<
    serializers.VersionIdResponseVersion.Raw,
    Humanloop.VersionIdResponseVersion
> = core.serialization.undiscriminatedUnion([PromptResponse, ToolResponse, DatasetResponse, EvaluatorResponse]);

export declare namespace VersionIdResponseVersion {
    type Raw = PromptResponse.Raw | ToolResponse.Raw | DatasetResponse.Raw | EvaluatorResponse.Raw;
}
