/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../../index";

/**
 * @example
 *     {}
 */
export interface CreateRunRequest {
    /** Dataset to use in this Run. */
    dataset?: Humanloop.CreateRunRequestDataset;
    /** Version to use in this Run. */
    version?: Humanloop.CreateRunRequestVersion;
    /** Whether the Run is orchestrated by Humanloop. If `True`, Humanloop will generate Logs for the Run; `dataset` and `version` must be provided. If `False`, a log for the Prompt/Tool should be submitted by the user via the API. */
    orchestrated?: boolean;
    /** If `True`, the Run will be initialized with existing Logs associated with the Dataset and Version. If `False`, the Run will be initialized with no Logs. Can only be set to `True` when both `dataset` and `version` are provided. */
    useExistingLogs?: boolean;
}
