/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateDirectoryRequest {
    /** Name to set for the directory. */
    name?: string;
    /** ID of the parent directory. Specify this to move directories. Starts with `dir_`. */
    parentId?: string;
}
