/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ListFilesFilesGetRequest {
    /**
     * Page offset for pagination.
     */
    page?: number;
    /**
     * Page size for pagination. Number of files to fetch.
     */
    size?: number;
    /**
     * Case-insensitive filter for file name.
     */
    name?: string;
    /**
     * Path of the directory to filter for. Returns files in this directory and all its subdirectories.
     */
    path?: string;
    /**
     * Filter to include only template files.
     */
    template?: boolean;
    /**
     * List of file types to filter for.
     */
    type?: Humanloop.FileType | Humanloop.FileType[];
    /**
     * Case-sensitive filter for files with a deployment in the specified environment. Requires the environment name.
     */
    environment?: string;
    /**
     * Field to sort files by
     */
    sortBy?: Humanloop.FileSortBy;
    /**
     * Direction to sort by.
     */
    order?: Humanloop.SortOrder;
    /**
     * Whether to include the raw file content in the response. Currently only supported for Agents and Prompts.
     */
    includeRawFileContent?: boolean;
}
