/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetEvaluatorsIdGetRequest {
    /**
     * A specific Version ID of the Evaluator to retrieve.
     */
    versionId?: string;
    /**
     * Name of the Environment to retrieve a deployed Version from.
     */
    environment?: string;
}
