/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Humanloop from "../../../../index";

/**
 * @example
 *     {
 *         size: 1
 *     }
 */
export interface ListEvaluatorsGetRequest {
    /**
     * Page offset for pagination.
     */
    page?: number;
    /**
     * Page size for pagination. Number of Evaluators to fetch.
     */
    size?: number;
    /**
     * Case-insensitive filter for Evaluator name.
     */
    name?: string;
    /**
     * Case-insensitive filter for users in the Evaluator. This filter matches against both email address and name of users.
     */
    userFilter?: string;
    /**
     * Field to sort Evaluators by
     */
    sortBy?: Humanloop.FileSortBy;
    /**
     * Direction to sort by.
     */
    order?: Humanloop.SortOrder;
}
