/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Humanloop from "../../../../../api/index";
import * as core from "../../../../../core";
import { RunSyncEvaluationRequestEvaluator } from "../../types/RunSyncEvaluationRequestEvaluator";

export const RunSyncEvaluationRequest: core.serialization.Schema<
    serializers.RunSyncEvaluationRequest.Raw,
    Humanloop.RunSyncEvaluationRequest
> = core.serialization.object({
    fileId: core.serialization.property("file_id", core.serialization.string()),
    evaluator: RunSyncEvaluationRequestEvaluator,
    evaluatorVersionId: core.serialization.property("evaluator_version_id", core.serialization.string().optional()),
    logIds: core.serialization.property("log_ids", core.serialization.list(core.serialization.string()).optional()),
    datapointIds: core.serialization.property(
        "datapoint_ids",
        core.serialization.list(core.serialization.string()).optional()
    ),
    promptVersionId: core.serialization.property("prompt_version_id", core.serialization.string().optional()),
});

export declare namespace RunSyncEvaluationRequest {
    interface Raw {
        file_id: string;
        evaluator: RunSyncEvaluationRequestEvaluator.Raw;
        evaluator_version_id?: string | null;
        log_ids?: string[] | null;
        datapoint_ids?: string[] | null;
        prompt_version_id?: string | null;
    }
}
