/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "prv_Wu6zx1lAWJRqOyL8nWuZk"
 *     }
 */
export interface LogsDeleteRequest {
    /**
     * Unique identifiers for the Logs to delete.
     */
    id?: string | string[];
}
