/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Humanloop from "../../../../api/index";
import * as core from "../../../../core";
import { FileEnvironmentVariableRequest } from "../../../types/FileEnvironmentVariableRequest";

export const Response: core.serialization.Schema<
    serializers.tools.getEnvironmentVariables.Response.Raw,
    Humanloop.FileEnvironmentVariableRequest[]
> = core.serialization.list(FileEnvironmentVariableRequest);

export declare namespace Response {
    export type Raw = FileEnvironmentVariableRequest.Raw[];
}
